### ISSUE TITLE
Geocoder vs GeocodingClient

### ISSUE THREAD

**Issue by tsusanka** [Clevis/GeolocationBase#2]
Moc nerozumím, jaký je mezi nima rozdíl. Možná GeocodingClient má být jakože implementace pomocí googlu? Pak bych to nazval GoogleGeocodingClient. A především Geocoder nemá takové možnosti jako GeocodingClient. Druhý jmenovaný např. může vrátit celý výsledek GeocodingResponse, ale Geocoder vrací rovnou Position. Potřeboval jsem celý GeocodingResponse, abych mohl z GeocodingResponse vysosat alternativy (zadaná ulice nebyla jednoznačná).

Takže to chce
- dodělat do Geocoder alternativy
- přejmenovat

a zvážil bych, jestli to není celé zbytečně složité. Nechal bych jen Geocoder, který bude pracovat s google a bude to 10x přehlednější. A kdyby náhodou hrozilo, že se přidá Bing/OpenStreet.. tak bych to řešil...

PS: píšu to narychlo, případně dovysvětlím

**Comment by enzy** [comment]
> a zvážil bych, jestli to není celé zbytečně složité. Nechal bych jen Geocoder, který bude pracovat s google a bude to 10x přehlednější.

+1

**Comment by paranoiq** [comment]
asi bych to zjednodušil. říkal jsem že se mi to api vůbec nelíbí. původně to bylo také rozdělené na služba/client, ale jak o tom tak uvažuji, tak vlastně nevím odkud jinud bychom měli tyhle věci tahat. takže ta univerzálnost je nám asi na nic

když to pojmem jen jako clienta pro googlí služby, tak se může i lépe zpřístupnit ta response, protože ta je právě specifická jen pro google
